---

name: "Action Name"

on:
  push:

jobs:
  run_tests:
    name: "Test stacked environments"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: "bash -elo pipefail {0}"

    steps:
      - run: "env | sort"
      - uses: "actions/checkout@v3"
      - uses: "mamba-org/setup-micromamba@v1"
        with:
          init-shell: none
      - name: "Create Environments"
        run: |
          "${MAMBA_EXE}" create -f environment1.yml -n env1 -y
          "${MAMBA_EXE}" create -f environment2.yml -n env2 -y
      - run: |
          eval "$(${MAMBA_EXE} shell hook)"
          "${MAMBA_EXE}" activate env1
          "${MAMBA_EXE}" activate --stack env2
          echo "${PATH}"
      - run: tail -n 20 ~/.bashrc
      - run: env | sort
      - run: echo "${PATH}"
      - run: micromamba env list
        shell: bash -el {0}
      - run: echo "${PATH}"
        shell: bash -el {0}
      - run: gdal-config    # This is from env1
      - run: geos-config    # this is from env2
