---

name: "Action Name"

on:
  push:

jobs:
  run_tests:
    name: "Test stacked environments"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: "bash -elo pipefail {0}"

    steps:
      - run: "env | sort"
      - uses: "actions/checkout@v3"
      - uses: "mamba-org/setup-micromamba@v1"
        with:
          init-shell: none
      - name: Install env1
        run: |
          micromamba create -f environment1.yml -n env1 -y
      - name: Install env2
        run: |
          micromamba create -f environment2.yml -n env2 -y
      - run: tail -n 5 ~/.bashrc
      - run: echo "${PATH}"
      - run: |
          eval "$(micromamba shell hook)"
          micromamba activate env1
          micromamba activate --stack env2
          echo "${PATH}"
          proj -lu
          geos-config --version
